server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    location /api-ventas/ {
        proxy_pass http://54.158.226.78:8080/;
    }

    location /api-despachos/ {
        proxy_pass http://184.72.145.76:8081/;
    }
}